### ISSUE TITLE
Error on very old machines (without SSE4)

### ISSUE THREAD

**Issue by hellocodelinux** [flathub/org.sdrangel.SDRangel#80]
Hello AsciiWolf, it's been a while! I'm LU9DCE.

I wanted to let you know that SDRangel (Flatpak) isn't working on several machines. This seems to be because it's being built with a more modern SSE, which causes an error on older machines, like first-generation Intel i3s.

As you may recall, we radio amateurs often use older PCs for our radios.

If possible, could you suggest compiling it with SSE or SSE2 at most? This should allow it to run on a wider range of machines. I believe adding -DCMAKE_CXX_FLAGS="-msse2" should make it work.

Best regards,

**Comment by AsciiWolf** [comment]
Hi Eduardo,

Shouldn't this already be fixed by [this PR](https://github.com/flathub/org.sdrangel.SDRangel/pull/65)?

**Comment by hellocodelinux** [comment]
I can't find the arrangement but
org.sdrangel.SDRangel.yaml
should have
-DCMAKE_CXX_FLAGS="-msse2"
after line 427"

**Comment by hellocodelinux** [comment]
el error que marca es
```
latpak run org.sdrangel.SDRangel 
2024-10-20 18:02:43.016 (W) Qt: Session management error: Could not open network socket
2024-10-20 18:02:43.030 (I) SDRangel 7.22.1 Qt 5.15.10 64b x86_64 KDE Flatpak runtime DSP Rx:24b Tx:16b PID 2
2024-10-20 18:02:43.036 (I) MainSettings::MainSettings: settings file: format: 0 location: /home/eduardo/.var/app/org.sdrangel.SDRangel/config/f4exb/SDRangel.conf
2024-10-20 18:02:48.449 (W) qUncompress: Input data is corrupted
2024-10-20 18:02:48.449 (W) qUncompress: Input data is corrupted
2024-10-20 18:02:48.449 (W) qUncompress: Input data is corrupted
2024-10-20 18:02:48.449 (W) qUncompress: Input data is corrupted
2024-10-20 18:02:49.433 (I) PluginManager::loadPluginsDir: loaded plugin libantennatools.so
2024-10-20 18:02:49.440 (I) PluginManager::loadPluginsDir: loaded plugin libaprs.so
2024-10-20 18:02:49.441 (I) PluginManager::loadPluginsDir: loaded plugin libbeamsteeringcwmod.so
2024-10-20 18:02:49.442 (I) PluginManager::loadPluginsDir: loaded plugin libchanalyzer.so
2024-10-20 18:02:49.443 (I) PluginManager::loadPluginsDir: loaded plugin libchannelpower.so
2024-10-20 18:02:49.477 (I) PluginManager::loadPluginsDir: loaded plugin libdemodadsb.so
2024-10-20 18:02:49.478 (I) PluginManager::loadPluginsDir: loaded plugin libdemodais.so
2024-10-20 18:02:49.479 (I) PluginManager::loadPluginsDir: loaded plugin libdemodam.so
2024-10-20 18:02:49.481 (I) PluginManager::loadPluginsDir: loaded plugin libdemodapt.so
2024-10-20 18:02:49.482 (I) PluginManager::loadPluginsDir: loaded plugin libdemodatv.so
2024-10-20 18:02:49.483 (I) PluginManager::loadPluginsDir: loaded plugin libdemodbfm.so
2024-10-20 18:02:49.484 (I) PluginManager::loadPluginsDir: loaded plugin libdemodchirpchat.so
2024-10-20 18:02:49.486 (I) PluginManager::loadPluginsDir: loaded plugin libdemoddab.so
2024-10-20 18:02:49.532 (I) PluginManager::loadPluginsDir: loaded plugin libdemoddatv.so
2024-10-20 18:02:49.533 (I) PluginManager::loadPluginsDir: loaded plugin libdemoddsc.so
2024-10-20 18:02:49.535 (I) PluginManager::loadPluginsDir: loaded plugin libdemoddsd.so
2024-10-20 18:02:49.536 (I) PluginManager::loadPluginsDir: loaded plugin libdemodendoftrain.so
2024-10-20 18:02:49.538 (I) PluginManager::loadPluginsDir: loaded plugin libdemodfreedv.so
2024-10-20 18:02:49.539 (I) PluginManager::loadPluginsDir: loaded plugin libdemodft8.so
2024-10-20 18:02:49.540 (I) PluginManager::loadPluginsDir: loaded plugin libdemodils.so
2024-10-20 18:02:49.541 (I) PluginManager::loadPluginsDir: loaded plugin libdemodm17.so
2024-10-20 18:02:49.542 (I) PluginManager::loadPluginsDir: loaded plugin libdemodnavtex.so
2024-10-20 18:02:49.543 (I) PluginManager::loadPluginsDir: loaded plugin libdemodnfm.so
2024-10-20 18:02:49.544 (I) PluginManager::loadPluginsDir: loaded plugin libdemodpacket.so
2024-10-20 18:02:49.545 (I) PluginManager::loadPluginsDir: loaded plugin libdemodpager.so
2024-10-20 18:02:49.546 (I) PluginManager::loadPluginsDir: loaded plugin libdemodradiosonde.so
2024-10-20 18:02:49.547 (I) PluginManager::loadPluginsDir: loaded plugin libdemodrtty.so
2024-10-20 18:02:49.548 (I) PluginManager::loadPluginsDir: loaded plugin libdemodssb.so
2024-10-20 18:02:49.549 (I) PluginManager::loadPluginsDir: loaded plugin libdemodvor.so
2024-10-20 18:02:49.550 (I) PluginManager::loadPluginsDir: loaded plugin libdemodwfm.so
2024-10-20 18:02:49.551 (I) PluginManager::loadPluginsDir: loaded plugin libdoa2.so
2024-10-20 18:02:49.552 (I) PluginManager::loadPluginsDir: loaded plugin libfeatureafc.so
2024-10-20 18:02:49.553 (I) PluginManager::loadPluginsDir: loaded plugin libfeatureais.so
2024-10-20 18:02:49.554 (I) PluginManager::loadPluginsDir: loaded plugin libfeatureambe.so
2024-10-20 18:02:49.555 (I) PluginManager::loadPluginsDir: loaded plugin libfeaturedemodanalyzer.so
2024-10-20 18:02:49.556 (I) PluginManager::loadPluginsDir: loaded plugin libfeaturegs232controller.so
``

**Comment by hellocodelinux** [comment]
Hey, I wanted to let you know that compiling directly on Debian stable works great... but when I run it via Flatpak, it doesn't.

**Comment by hellocodelinux** [comment]
One of the errors is that for the software, I created the SDRangel.conf,
and the folder ~/.var/app/org.sdrangel.SDRangel/config/f4exb/ must be created.
Not only that, but there is also an error:
qUncompress: Input data is corrupted
which prevents it from creating the SDRangel.conf.
If I create the file, the error goes away, but the software still doesn't start.

Tell me how I can help.
Compiling everything is not possible for me because I'm using very old PCs.
I have several SDR models that I usually use with SDRangel on Debian.

**Comment by AsciiWolf** [comment]
I need to assess first what potential performance issues and other problems can the `-msse2` bring. The performance drawbacks were minimal with _ARCH_OPT_ set to `nehalem`, but I am not sure about that one. And even SSE4 is quite old at this point.

**Comment by hellocodelinux** [comment]
ok on my machines it works fine
intel i3 first generation, pentiun dual and intel q6600
i have several sdr
i have a question could another flatpak be created with the name sdrangel-oldpc
i can try it on my machines
but there is a time when i stopped using github
that's why i stopped collaborating with flatpak
github used my own code with copyright and i had legal problems

**Comment by AsciiWolf** [comment]
I have assessed this and decided to not support older CPUs than the Nehalem architecture. Sorry, but even Nehalem (launched in November 11, 2008 - 17 years ago!) can be considered as very old at this point and since this Flatpak has problems (and SIGILL crashes) even with much newer CPUs (because of compiler bugs), I am not enabling even more legacy optimization that can bring new problems and crashes. Closing this ticket.
